### PR TITLE
Use golang:alpine image

### PR DESCRIPTION
**Pull request by xbglowx**

### CODE REVIEW

**Comment by xbglowx** [comment]
@docker-infra/infra @tescherm

**Comment by binman-docker** [comment]
LGTM

**Comment by tescherm** [comment]
thx

**Comment by tescherm** [comment]
have you looked at trying to build an image that just includes the go binary?

**Comment by xbglowx** [comment]
@tescherm I haven't yet, but can in the future.

The recent change is better than what we recently had. I could see moving to a purely go binary image if we were really concerned about space and had to run multiple containers based on this image, but that is currently not the case.

**Pull request merged**
