### PR TITLE
Removal of images were failing since the original logic didn't look a…

### PR DESCRIPTION
**Pull request by xbglowx**
…t intermediate images (parents)
- Update help in regards to -ca and -ia
- Switch to use go 1.4.2
- Update to use latest dockerclient. https://github.com/samalba/dockerclient/pull/130
  adds support to ListImages to list all images
- Don't exit if can't inspect or get container exit time; continue instead

### CODE REVIEW

**Comment by xbglowx** [comment]
@discordianfish

**Comment by xbglowx** [comment]
Looks like I have a bug in my logic for determining if a image is a parent of another. Working on fixing this soon.

**Comment by discordianfish** [comment]
@xbglowx I think there was never logic for skipping if a image is parent of another: Docker will simply refuse to remove such image and you just need to ignore the error in that case.
Beside the, LGTM.

**Comment by xbglowx** [comment]
Tested in stage and prod for many days without problems.

**Pull request merged**
